### ISSUE TITLE
Responsive classes

### ISSUE THREAD

**Issue by visualcookie** [tzi/herow.scss#2]
Hi,

I used your grid generator like in the example at the end of the README:
``` scss
@include Herow-class-generator($grid-columns, $grid-gutter);

@media (max-width: 799px) {
   @include Herow-class-generator($grid-columns, $grid-gutter, '', '-md');
}

@media (max-width: 599px) {
   @include Herow-class-generator($grid-columns, $grid-gutter, '', '-xs');
}
```

Problem is, that the output doesn't look like expected.
``` css
.-mdcol-1 { width: 8.33333%; }
```

I want, that the classes appear like so:
``` css
.col-md-$num
```

Is that in someway possible? Or is there just a way, to avoid using tons of classes on a single element and just break some cols, if they don't fit, like setting specific cols to display: block; or something?

Would be quite useful if you could answer both.

**Comment by tzi** [comment]
Hi!

Sorry, I didn't notice this issue until today. 

You can not easily generate a class like `.col-md-1`. You can either generate:

 * with a prefix, like `.md-col-1`  
with `@include Herow-class-generator($grid-columns, $grid-gutter, '', '-md');`
 * or with a suffix, like `.col-1-md`  
with `@include Herow-class-generator($grid-columns, $grid-gutter, '', '', '-md');`

I'm not sure I understood the second question.

You can set a column as a "block" column, with the following code:

```scss
.col-block {
  @include Herow-column-flow('block');
}
```

It will generate a simple code, so can just use the generated code:

```css
.col-block {
  display: block;
  float: none;
}
```
